name: Publish Release to PyPI

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build:
    runs-on:  ubuntu-latest
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      # See: https://github.com/pypa/gh-action-pypi-publish#trusted-publishing
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'  # Should always be the minimum supported Python version
        cache: 'pip'
        cache-dependency-path': 'requirements.txt'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build with hatch
      run: |
        hatch build --clean
    - name: upload release to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
